# Generated by Django 4.2.4 on 2023-08-19 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 8, 46, 47, 87112, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
